### ISSUE TITLE
Overwrite Option

### ISSUE THREAD

**Issue by skibulk** [moxiecode/plupload-handler-php#1]
This code is so well written, thank you!

If John Doe uploads a file named "gangster.jpg" and Jane Doe uploads a completely different image named "gangster.jpg", the previous file is overwritten by this handler. Could you add an option to disable overwrites? Also another option to keep both files? For example, rewriting to "gangster(2).jpg".

**Comment by jayarjo** [comment]
@Ne4to777, but `unique_names` does just that, what's the point?
